/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "who.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

char **
get_logged_users_1(void *argp, CLIENT *clnt)
{
	static char *clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET_LOGGED_USERS,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int main(int argc, char *argv[]) {
	CLIENT *client;
	char** result;

    if(argc != 2) {
		printf("Usage: %s <hostname>\n",argv[0]);
		return 1;
    }

    client = clnt_create(argv[0], WHOPROG, WHOVERS, "udp");
    if(client == NULL) {
        clnt_pcreateerror(server);
		return 1;
    }

    result = get_logged_users_1(NULL, client);
    if(result == NULL) {
        clnt_perror(client, argv[1]);
		return 1;
    }

	printf("Currently logged-in users:\n%s", *result);

    clnt_destroy(client);
    return 0;
}
