/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "who.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <utmp.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

char** get_logged_users_1_svc(void *a, struct svc_req *b) {
    struct utmp *entry;
    static const size_t MAX_BUFFER_SIZE = 100000; // Fixed buffer size
    char *result = NULL;

    if(result != NULL) {
        free(result);
        result = NULL;
    }
	result = (char *)malloc(MAX_BUFFER_SIZE);
    if (!result) {
        perror("Memory allocation failed");
        return NULL;
    }
    result[0] = '\0'; // Initialize the string
    size_t used_size = 0; // Tracks the current buffer usage

    // Initialize reading from the utmp file
    setutent();

    // Read entries from the utmp file
    while ((entry = getutent()) != NULL) {
        if (entry->ut_type == USER_PROCESS) { // Only process logged-in users
            char line[256];
            snprintf(line, sizeof(line), "%-16s %-16s %-16s\n",
                     entry->ut_user,
                     entry->ut_line,
                     entry->ut_host[0] ? entry->ut_host : "Local");

            size_t line_length = strlen(line);
            if (used_size + line_length >= MAX_BUFFER_SIZE) {
                // Stop if the buffer limit is exceeded
                fprintf(stderr, "Buffer limit exceeded: Cannot add more data.\n");
                break;
            }

            // Append the new line to the result string
            strcat(result, line);
            used_size += line_length;
        }
    }

    // Close the utmp file
    endutent();

    return &result;
}

static void
whoprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int fill;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GET_LOGGED_USERS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) get_logged_users_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (WHOPROG, WHOVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, WHOPROG, WHOVERS, whoprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (WHOPROG, WHOVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, WHOPROG, WHOVERS, whoprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (WHOPROG, WHOVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
